spring: 
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: samu
    password: pw1234
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: false
    show-sql: true
    open-in-view: false
  security:
    user:
      name: samu
      password: pw1234
      
server:
  port: 8443
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:keystore/localkeystore.p12
    key-store-password: pw1234
    key-alias: localkeypair
    